# remap the prefix
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# add mouse and color
set -g default-terminal "screen-256color"

# switching windows
bind -r h previous-window
bind -r l next-window
bind-key -n S-Left swap-window -t -1
bind-key -n S-Right swap-window -t +1

# bar thing at the bottom
set -g status-position bottom
set -g status-bg colour34
#set -g status-bg colour178
set -g status-fg black
set -g status-left ''
set -g status-right-length 50
set -g status-right "#[fg=colour0]%A, %d %b %Y %I:%M %p"
set -g status-left-length 20
setw -g mode-keys vi

setw -g window-status-current-format ' #I#[fg=colour250]:#[fg=colour20]#W#[fg=colour231]#F '
setw -g window-status-format ' #I#[fg=colour237]:#[fg=colour0]#W#[fg=colour231]#F '
set-option -g renumber-windows on

# history length
set-option -g history-limit 5000

# no escape delay for vim
set -s escape-time 0

#set -g default-path
#set-option -g default-command "exec /bin/bash"
set-option -g repeat-time 0 # so that tmux commands have no delay

# make tmux use zsh
set-option -g default-shell /bin/zsh

# bindings to resize panes
bind-key -r + resize-pane -U
bind-key -r - resize-pane -D
bind-key -r S-Left resize-pane -L
bind-key -r S-Right resize-pane -R

# visual mode for vim
bind-key -T copy-mode-vi 'v' send -X begin-selection

# tpm plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "tmux-plugins/tmux-yank"

run '~/.tmux/plugins/tpm/tpm'
